version: '3.8'

services:
  # Frontend web application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  # Backend monitoring service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    volumes:
      - ./backend:/app
    restart: unless-stopped
    # Use cron-like scheduling with a custom entrypoint
    entrypoint: ["sh", "-c", "while true; do python /app/monitor.py; sleep 300; done"] 